title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-contentful-data-import
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
contentful:
  spaces:
    - posts:
        space: c5rxotc5huuu
        access_token: c45d96adf15d611d2bcdf5b8770cd5cc0c2debb40df2b35ad4bd31f60c8c8d84
