title: Clearbit Sales Operations
description: >-
  Clearbit provides powerful products and data APIs to help your business grow. Contact enrichment, lead generation, financial compliance, and more...
baseurl: ""
url: ""
twitter:
  username: clearbit
defaults:
  - scope:
      path: ""
    values:
      image: "https://sc-socialimage.herokuapp.com/"
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-contentful-data-import
- jekyll-toc
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
contentful:
  spaces:
    - posts:
        space: c5rxotc5huuu
        access_token: c45d96adf15d611d2bcdf5b8770cd5cc0c2debb40df2b35ad4bd31f60c8c8d84
        destination: ""
page_gen:
  - data: 'posts.post'
    template: 'post'
    index_files: true
    name: 'title'
    dir: 'posts'
